
## Please select one option between each set of adjectives "{{{adjectives_q}}}"


```{r {{{adjectives_q_code}}}_input}
input <- list(selected_adj_q = "{{{adjectives_q}}}")
adj_select_df <-
  adj_ldf %>%
    filter(str_detect(question_text, input$selected_adj_q))
```


### Overall Agreement

```{r {{{adjectives_q_code}}}_plot_overall}
adj_select_df %>%
  ggplot(aes(x = response)) +
  geom_bar() +
  scale_x_discrete(guide = guide_axis(n.dodge = 2))
```

### Agreement by Gender

```{r {{{adjectives_q_code}}}_plot_gender}
adj_select_df %>%
  group_by(gender) %>%
  count(response, name = "count", .drop = FALSE) %>%
  mutate(prop = count / sum(count)) %>%
  ggplot(aes(x = response, fill = gender)) %>%
  stack_freq_prop(title = input$selected_agr_q)
```



### Agreement by Race

```{r {{{adjectives_q_code}}}_plot_race}
adj_select_df %>%
  simplify_race_var() %>%
  group_by(race) %>%
  count(response, name = "count", .drop = FALSE) %>%
  mutate(prop = count / sum(count)) %>%
  ggplot(aes(x = response, fill = race)) %>%
  stack_freq_prop(title = input$selected_agr_q)
```

